inseri-swiss/inseri-core-wp

.prettierrc, .prettierrc.yml, docs/openapi.yml, includes/db.php, includes/rest_api.php, includes/utils.php, inseri-core.php
fix inseri-swiss/inseri/issues/61
=> add REST api for data sources

src/admin-panel/DetailView.tsx, src/admin-panel/TableComponents.tsx, src/blocks/dropdown/block.json, src/components/InseriThemeProvider.tsx
fix inseri-swiss/inseri-swiss#40
`withGlobalStyles` did override theme style
=> Bugfix styling

package-lock.json, package.json, src/blocks/image/Component.tsx, src/blocks/image/block.json, src/blocks/image/hydration.tsx, src/blocks/image/index.tsx, src/blocks/image/state.tsx, src/blocks/textEditor/Component.tsx, src/globalScript/utils.ts
fix inseri-swiss/inseri-swiss/issues/5
=> block: image block

src/blocks/python/Component.tsx
fix inseri-swiss/inseri-swiss/issues/58
=> fix: remove delay

package-lock.json, package.json, src/blocks/html/Component.tsx, src/blocks/html/block.json, src/blocks/html/hydration.tsx, src/blocks/html/index.tsx, src/blocks/html/state.tsx, src/blocks/html/style.scss, src/blocks/python/worker.ts
fix inseri-swiss/inseri-swiss/issues/51
=> html block

.github/workflows/npm-run.yml, package-lock.json, package.json, src/ApiServer.ts, src/blocks/fileDrop/Component.tsx, src/blocks/fileDrop/block.json, src/blocks/fileDrop/hydration.tsx, src/blocks/fileDrop/index.tsx, src/blocks/fileDrop/state.tsx, src/utils.tsx
fix inseri-swiss/inseri-swiss/issues/34
=> File Drop block

src/ApiServer.ts, src/blocks/zenodo/Component.tsx, src/blocks/zenodo/block.json, src/blocks/zenodo/hydration.tsx, src/blocks/zenodo/index.tsx, src/blocks/zenodo/state.tsx, src/utils.tsx
fix inseri-swiss/inseri-swiss/issues/13
=> Zenodo Block

docs/getting-started.md, mkdocs.yml
- mentioned in https://github.com/inseri-swiss/inseri-swiss/issues/59
=> docs: add release info to documentation

inseri-core.php, package.json, readme.txt
related inseri-swiss/inseri-swiss/issues/91
=> apply plugin review

README.md
- add WordPress badge
- update Playground badge
Part of https://github.com/inseri-swiss/inseri-swiss/issues/93
=> chore: add WordPress badge

docs/blocks/cytoscape.md, docs/blocks/mediaCollection.md, docs/blocks/plotly.md, docs/blocks/python.md, docs/blocks/textEditor.md, docs/blocks/webApi.md, docs/blocks/zenodo.md, docs/features/DataFlow.md, docs/tutorials/data-mapping-with-python.md, docs/tutorials/hello-world.md, mkdocs.yml
partial fixes from https://github.com/inseri-swiss/inseri-swiss/issues/102 
- add Cytoscape block
- add Data Flow
- add details about hidden blocks
=> Improve docs

docs/features/DataFlow.md, docs/getting-started.md, docs/tutorials/data-mapping-with-python.md, docs/tutorials/hello-world.md
partial fixes from https://github.com/inseri-swiss/inseri-swiss/issues/102 
- rename some parts
=> docs: fix terminology

package-lock.json, package.json, src/blocks/localFileImport/edit.tsx, src/blocks/table/block.json, src/blocks/table/edit.tsx, src/blocks/table/hydration.tsx, src/blocks/table/index.tsx, src/blocks/table/state.tsx, src/blocks/table/utils.ts, src/blocks/table/view.tsx
fix inseri-swiss/inseri-swiss/issues/52
=> add table block

README.md, docs/features/dataFlow.md, docs/features/hideInvisibleBlocks.md, docs/features/sidebar.md, docs/index.md, readme.txt
fix https://github.com/inseri-swiss/inseri-swiss/issues/114
=> docs: update inseri sidebar

src/blocks/cytoscape/edit.tsx, src/blocks/dataTable/edit.tsx, src/blocks/download/edit.tsx, src/blocks/dropdown/edit.tsx, src/blocks/html/edit.tsx, src/blocks/iiifViewer/edit.tsx, src/blocks/image/edit.tsx, src/blocks/plotly/edit.tsx, src/blocks/python/ExtendedView.tsx, src/blocks/python/edit.tsx, src/blocks/textViewer/edit.tsx, src/blocks/textViewer/state.tsx, src/blocks/webApi/edit.tsx, src/components/SelectWithAction.tsx, src/components/SourceSelect.tsx, src/components/index.tsx, src/globalScript/editor/Sidebar.tsx, src/globalScript/lighthouse.tsx
fix inseri-swiss/inseri-swiss/issues/121
=> improve UX for selecting blocks

.wordpress-org/blueprints/blueprint.json
add `blueprint.json` related to https://github.com/inseri-swiss/inseri-swiss/issues/126
=> feat: enable live preview

.github/dependabot.yml, src/blocks/javascript/worker.ts
fix inseri-swiss/inseri-swiss/issues/130
=> fix js block async

.wordpress-org/blueprints/blueprint.json, readme.txt
fix https://github.com/inseri-swiss/inseri-swiss/issues/131
=> chore: update wp tags

package-lock.json, package.json, src/components/InseriThemeProvider.tsx, src/globalScript/editor/Sidebar.tsx
fix inseri-swiss/inseri-swiss/issues/136
=> support site editor

src/blocks/python/worker.ts, webpack.config.js
fix inseri-swiss/inseri-swiss/issues/143
=> fix: pyodide webpack config

docs/features/open_citable.md, docs/how-to/deposit_content.md, docs/how-to/playground.md, docs/tutorials/hello_world.md, mkdocs.yml
- related to https://github.com/inseri-swiss/inseri-swiss/issues/138
- fix https://github.com/inseri-swiss/inseri-swiss/issues/28
=> Feat/improve docs sprint 18 - Part 2

src/blocks/download/block.json, src/blocks/download/edit.tsx, src/blocks/download/index.tsx, src/blocks/download/view.tsx
fix inseri-swiss/inseri-swiss/issues/90
=>  custom file extension

src/blocks/javascript/state.tsx, src/blocks/javascript/view.tsx, src/blocks/python/state.tsx, src/blocks/python/view.tsx, src/blocks/rCode/state.tsx, src/components/ExtendedView.tsx
relate inseri-swiss/inseri-swiss/issues/94
relate inseri-swiss/inseri-swiss/issues/139
=> fix output bug in python and js block

docs/blocks/rCode.md, docs/how-to/r_packages.md, docs/how-to/visualizations.md, mkdocs.yml
Takes care of https://github.com/inseri-swiss/inseri-swiss/issues/145:
=> docs: improve docs sprint 19 - 2

docs/blocks/overview.md, docs/blocks/textEditor.md, docs/blocks/webApi.md
Part of https://github.com/inseri-swiss/inseri-swiss/issues/152 
- document the iframe bug https://github.com/inseri-swiss/inseri-swiss/issues/141
=> Improve docs sprint 20 - 1

.wordpress-org/blueprints/blueprint.json, docs/blocks/python.md, docs/blocks/rCode.md, docs/how-to/python_packages.md
Part of https://github.com/inseri-swiss/inseri-swiss/issues/152 
- update blueprint
- remove docs regarding requests package
- update Python docs - saved file as output
=> Improve docs sprint 20 - 2

src/blocks/cytoscape/hydration.tsx, src/blocks/dataTable/hydration.tsx, src/blocks/download/hydration.tsx, src/blocks/dropdown/hydration.tsx, src/blocks/export/hydration.tsx, src/blocks/html/hydration.tsx, src/blocks/iiifViewer/hydration.tsx, src/blocks/image/hydration.tsx, src/blocks/javascript/hydration.tsx, src/blocks/localFileImport/hydration.tsx, src/blocks/mediaCollection/hydration.tsx, src/blocks/plotly/hydration.tsx, src/blocks/python/hydration.tsx, src/blocks/rCode/hydration.tsx, src/blocks/slider/hydration.tsx, src/blocks/textEditor/hydration.tsx, src/blocks/textViewer/hydration.tsx, src/blocks/webApi/hydration.tsx, src/blocks/zenodo/hydration.tsx
related inseri-swiss/inseri-swiss/issues/151
=> fix blockname issue

docs/blocks/textEditor.md
Part of https://github.com/inseri-swiss/inseri-swiss/issues/152 
- remove iframe note from the text editor block
=> Improve docs sprint 20 - 3

docs/blocks/share.md, mkdocs.yml, readme.txt, src/blocks/share/block.json
Part of https://github.com/inseri-swiss/inseri-swiss/issues/152 
- add Share block
=> Improve docs sprint 20 - 4

docs/blocks/share.md
=> Improve docs sprint 20 - 5

docs/blocks/python.md, docs/features/hide_invisible_blocks.md, docs/how-to/work_with_files.md, docs/index.md
Part of https://github.com/inseri-swiss/inseri-swiss/issues/157 :
- add a reference to the CSV -> JSON to the blog entry https://inseri.swiss/2024/05/global-student-visa-cost/
- mention Pyodide in https://docs.inseri.swiss/blocks/python/ 
- remove subscribe from docs
- fix typo in share https://docs.inseri.swiss/features/share_state/
=> Improve docs sprint 21 - 1

README.md, docs/index.md, readme.txt
=> Fix inseri swiss links
